### ISSUE TITLE
cmailPro Accounts

### ISSUE THREAD

**Issue by KatTemelkova** [communigate/communigate-cpanel-adaptor#10]
Accounts > проблем при задаването на паролата: могат да се слагат празно място и букви на кирилица.

**Comment by a-katsarov** [comment]
А какъв е проблемът с това? Някаква грешка ли дава? Дай малко повече подробности.

**Comment by IvetPetrova** [comment]
На Катето и се струва странно, че в паролата могат да присъстват такива символи (на криилица) и празни места. Не и е логично.

**Comment by a-katsarov** [comment]
Не е странно. Нормално е. Колкото по-голям набор от символи ползваш в паролата си, толкова по-сигурна е тя. Аз редовно ползвам интервали в паролите си. Технически също няма ограничения.
